name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-
    - name: Build
      run: |
        yarn
        yarn build
